Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: this-is-not-a-real-bucket-name-234364537649827370
    Metadata:
      Purpose: "Creating a S3 bucket"
      Reviewed: "07-17-2026"
      Owner: "John Smith"
      Contact: "Johnsmith@gmail.com"
      