Mappings:
  DevMap: 
    Tony:
      Title: QA
    Ben:
      Title: Cloud Engineer
    

Parameters:
  InputBucketName:
    Type: String
    Description: Please enter in your desired bucket name
  InputDeveloperName:
    Type: String
    Description: Please enter in your name
    Default: 'Ben'
  EnvInput:
    Type: String
    Description: Input Environment
    AllowedValues:
      - Dev
      - Test
      - Prod

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
      Tags:
        - Key: Developer
          Value: !Ref InputDeveloperName
        - Key: Envirionment
          Value: !Ref EnvInput
        - Key: Profession
          Value: !FindInMap [DevMap, !Ref InputDeveloperName, Field]
    Metadata:
      Purpose: "Creating a S3 bucket"
      Reviewed: "07-17-2026"
      Owner: "John Smith"
      Contact: "Johnsmith@gmail.com"
      